from yacs.config import CfgNode as CN

_C = CN()

# model default values
_C.MODEL = CN()
_C.MODEL.TYPE = "RNN"
_C.MODEL.INPUT_SIZE = 19
_C.MODEL.OUTPUT_SIZE = 3
_C.MODEL.HIDDEN_SIZE = 128
_C.MODEL.NUM_LAYERS = 2
_C.MODEL.SEQUENCE_LENGTH = 28
_C.MODEL.DROPOUT = 0.2
_C.MODEL.BEST_CONFIG = None

# Solver default values
_C.SOLVER = CN()
_C.SOLVER.NUM_EPOCHS = 100
_C.SOLVER.BATCH_SIZE = 100
_C.SOLVER.LR = 0.001
_C.SOLVER.BASE_LR = 0.001
_C.SOLVER.LOG_STEP = 500
_C.SOLVER.GPUS_PER_TRIAL = 1
_C.SOLVER.LOSS = 'MSE'
_C.SOLVER.OPTIMIZER_NAME = 'Adam'
_C.SOLVER.SCHEDULER = 'StepLR'
_C.SOLVER.SCHEDULER_STEP_SIZE = 10
_C.SOLVER.SCHEDULER_GAMMA = 0.1


# Data default values
_C.DATA = CN()
_C.DATA.TRAIN_DATA_DIR = "./data/2D/generated_data"
_C.DATA.EVAL_DATA_DIR = "./data/2D/evaluation_data"
_C.DATA.SETTING = '2D'
_C.DATA.ENVIRONMENT = 'fbcampus'
_C.DATA.SETUP = 'appended'
_C.DATA.TEST_SIZE = 0.2

# Output default values
_C.OUTPUT = CN()
_C.OUTPUT.OUTPUT_DIR = "./output"
_C.OUTPUT.PLOT = False