DATA:
  ENVIRONMENT: fbcampus
  EVAL_DATA_DIR: ./data/1D/evaluation_data
  SETTING: 1D
  TRAIN_DATA_DIR: ./data/1D/generated_data
  SETUP: appended # appended or separated

MODEL:
  HIDDEN_SIZE: 128
  INPUT_SIZE: 9
  # TYPE: SimpleRNN
  TYPE: RNN 
  # TYPE: LSTM
  NUM_LAYERS: 2
  OUTPUT_SIZE: 1
  SEQUENCE_LENGTH: 28

OUTPUT:
  OUTPUT_DIR: ./logs/separate/experiments_1D
  PLOT: True

SOLVER:
  BATCH_SIZE: 100
  LOG_STEP: 20
  LR: 0.001
  NUM_EPOCHS: 200
  GPUS_PER_TRIAL: 1
