DATA:
  ENVIRONMENT: fbcampus
  EVAL_DATA_DIR: ./data/2D/evaluation_data
  SETTING: 2D
  TRAIN_DATA_DIR: ./data/2D/generated_data
  SETUP: separated # appended or separated

MODEL:
  HIDDEN_SIZE: 128
  INPUT_SIZE: 19
  # TYPE: SimpleRNN
  # INPUT_SIZE: 18 # no alpha value
  TYPE:  RNN # RNN or LSTM, LSTM_ln, GRU
  NUM_LAYERS: 2
  OUTPUT_SIZE: 3
  SEQUENCE_LENGTH: 28

OUTPUT:
  OUTPUT_DIR: ./output
  PLOT: True

SOLVER:
  BATCH_SIZE: 100
  LOG_STEP: 500
  LR: 0.001
  NUM_EPOCHS: 200
  GPUS_PER_TRIAL: 1
